#!/usr/bin/env node

const readline = require('readline');
const fs = require('fs');
const path = require('path');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

function question(prompt) {
  return new Promise((resolve) => {
    rl.question(prompt, resolve);
  });
}

async function setup() {
  console.log('\n🚀 Notion Meeting Sync - Interactive Setup\n');
  console.log('This wizard will help you configure the meeting sync tool.\n');

  const config = {};

  // Step 1: Personal Notion Integration
  console.log('📋 STEP 1: Personal Notion Integration');
  console.log('   1. Go to https://www.notion.so/my-integrations');
  console.log('   2. Click "New integration"');
  console.log('   3. Name it "Personal Meeting Sync" (or whatever you prefer)');
  console.log('   4. Copy the integration token (starts with "secret_")\n');

  config.PERSONAL_NOTION_TOKEN = await question('Enter your PERSONAL Notion integration token: ');

  // Step 2: Personal Database
  console.log('\n📋 STEP 2: Personal Meetings Database');
  console.log('   1. Open your personal meetings database in Notion');
  console.log('   2. Go to Settings → Connections → Find your "Personal Meeting Sync" integration');
  console.log('   3. Click your integration and select your meetings database to give it access');
  console.log('   4. Copy the database URL from your browser\n');
  console.log('   Example URL: https://www.notion.so/abc123def456?v=...');
  console.log('   Database ID: abc123def456\n');

  const personalDbUrl = await question('Enter your personal database URL or ID: ');
  config.PERSONAL_DATABASE_ID = extractDatabaseId(personalDbUrl);

  // Step 3: Category Configuration
  console.log('\n📋 STEP 3: Category Filter Configuration');
  console.log('   What property do you use to tag meetings for your company?');
  console.log('   (Common names: "Category", "Tags", "Type")\n');

  config.CATEGORY_PROPERTY_NAME = await question('Property name (default: Category): ') || 'Category';

  console.log('\n   What value in that property indicates a company meeting?');
  console.log('   (For example: "Bluon", "Company", "Work")\n');

  config.CATEGORY_FILTER_VALUE = await question('Filter value: ');

  // Step 4: Company Notion Integration
  console.log('\n📋 STEP 4: Company Notion Integration');
  console.log('   1. Go to https://www.notion.so/my-integrations in your COMPANY workspace');
  console.log('   2. Click "New integration"');
  console.log('   3. Name it "Meeting Sync" (or whatever you prefer)');
  console.log('   4. Copy the integration token\n');

  config.COMPANY_NOTION_TOKEN = await question('Enter your COMPANY Notion integration token: ');

  // Step 5: Company Database
  console.log('\n📋 STEP 5: Company Meetings Database');
  console.log('   1. Open (or create) your company meetings database in Notion');
  console.log('   2. Make sure it has these 3 properties:');
  console.log('      - A title property (any name) - REQUIRED');
  console.log('      - URL (type: URL) - REQUIRED');
  console.log('      - Transcript (type: Text) - REQUIRED');
  console.log('   3. Go to Settings → Connections → Find your "Meeting Sync" integration');
  console.log('   4. Click your integration and select your company database to give it access');
  console.log('   5. Copy the database URL from your browser\n');

  const companyDbUrl = await question('Enter your company database URL or ID: ');
  config.COMPANY_DATABASE_ID = extractDatabaseId(companyDbUrl);

  // Generate .env file
  console.log('\n📝 Generating .env file...');

  const envContent = `# Notion Meeting Sync Configuration
# Generated by setup wizard

# Personal Notion Integration
PERSONAL_NOTION_TOKEN=${config.PERSONAL_NOTION_TOKEN}
PERSONAL_DATABASE_ID=${config.PERSONAL_DATABASE_ID}

# Company Notion Integration
COMPANY_NOTION_TOKEN=${config.COMPANY_NOTION_TOKEN}
COMPANY_DATABASE_ID=${config.COMPANY_DATABASE_ID}

# Filter Configuration
CATEGORY_PROPERTY_NAME=${config.CATEGORY_PROPERTY_NAME}
CATEGORY_FILTER_VALUE=${config.CATEGORY_FILTER_VALUE}
`;

  fs.writeFileSync('.env', envContent);
  console.log('✅ .env file created!');

  // Display GitHub secrets for user to save
  console.log('\n📝 GitHub Secrets - SAVE THESE!');
  console.log('\n⚠️  Copy this list somewhere safe. You\'ll need it in the next step:\n');
  console.log('PERSONAL_NOTION_TOKEN');
  console.log(config.PERSONAL_NOTION_TOKEN);
  console.log('');
  console.log('COMPANY_NOTION_TOKEN');
  console.log(config.COMPANY_NOTION_TOKEN);
  console.log('');
  console.log('PERSONAL_DATABASE_ID');
  console.log(config.PERSONAL_DATABASE_ID);
  console.log('');
  console.log('COMPANY_DATABASE_ID');
  console.log(config.COMPANY_DATABASE_ID);
  console.log('');
  console.log('CATEGORY_PROPERTY_NAME');
  console.log(config.CATEGORY_PROPERTY_NAME);
  console.log('');
  console.log('CATEGORY_FILTER_VALUE');
  console.log(config.CATEGORY_FILTER_VALUE);
  console.log('\n✅ Configuration complete!');

  // Test the connection
  console.log('\n🧪 Would you like to test the connection now?');
  const testNow = await question('Test now? (y/n): ');

  if (testNow.toLowerCase() === 'y') {
    console.log('\n📡 Testing connection...');
    require('dotenv').config();
    try {
      await require('./sync-meetings.js');
    } catch (error) {
      console.error('\n❌ Test failed:', error.message);
      console.log('\nPlease check your configuration and try again.');
    }
  }

  console.log('\n✅ Setup complete!');
  console.log('\n📚 Next steps:');
  console.log('   1. Test locally: npm start');
  console.log('   2. Push to GitHub: git add . && git commit -m "Add config" && git push');
  console.log('   3. Add the secrets above to GitHub (Settings → Secrets → Actions)');
  console.log('\n🎉 You\'re all set!\n');

  rl.close();
}

function extractDatabaseId(input) {
  // Remove whitespace
  input = input.trim();

  // If it looks like a URL, extract the ID
  if (input.includes('notion.so')) {
    const match = input.match(/([a-f0-9]{32})/);
    return match ? match[1] : input;
  }

  // Remove dashes if present
  return input.replace(/-/g, '');
}

setup().catch(console.error);
